apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  ConnectionStrings: "mongodb://username:password@mongo-service:27017"
  DatabaseName: CatalogDb
  CollectionName: Products
  TypesCollection: Types
  BrandsCollection: Brands