apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: joelrdb/catalogapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name :  ASPNETCORE_URLS
              value: "http://+:80"
            - name: DatabaseSettings__ConnectionStrings
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: ConnectionStrings
            - name: DatabaseSettings__DatabaseName
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: DatabaseName
            - name: DatabaseSettings__CollectionName
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: CollectionName
            - name: DatabaseSettings__TypesCollection
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: TypesCollection
            - name: DatabaseSettings__BrandsCollection
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: BrandsCollection
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000
  type: NodePort
